server:
  port: 5556
spring:
  application:
    name: order-goods
  cloud:
    nacos:
      discovery:
        server-addr: 39.97.253.89:8848
  datasource:
    url: jdbc:mysql://localhost:3306/mytrading?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root #如果出错改123456
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
